/**
 * Static Cache Generator for AI Deep Dive
 * 
 * Usage: npm run generate-cache
 * 
 * This script:
 * 1. Reads all nodes from constants.ts
 * 2. Calls Gemini API for each node
 * 3. Saves results to services/staticCache.ts
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ESM __dirname equivalent
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
import 'dotenv/config';

const API_KEY = process.env.VITE_GOOGLE_API_KEY;

if (!API_KEY) {
    console.error('❌ VITE_GOOGLE_API_KEY is missing in .env');
    process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);

interface NodeData {
    id: string;
    label: string;
    category: string;
    year: number;
    description?: string;
    role?: string;
    primaryRole?: string;
    companyCategories?: string[];
    techCategoryL1?: string;
    marketCap?: { current?: string };
}

interface AIResponse {
    summary: string;
    significance: string;
    keyFacts: string[];
}

// Extract nodes from constants.ts
function extractNodes(): NodeData[] {
    const constantsPath = path.join(__dirname, '../constants.ts');
    const content = fs.readFileSync(constantsPath, 'utf-8');

    const nodes: NodeData[] = [];

    // Match createCompany, createPerson, createTech
    const regex = /create(Company|Person|Tech)\s*\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*(\d+)/g;
    let match;

    while ((match = regex.exec(content)) !== null) {
        const [, type, id, label, year] = match;
        nodes.push({
            id,
            label,
            category: type.toUpperCase(),
            year: parseInt(year),
        });
    }

    return nodes;
}

async function generateForNode(node: NodeData): Promise<AIResponse | null> {
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-001' });

    const prompt = `
You are an expert technology historian. Analyze the following entity in the context of computing and AI history.

Entity: "${node.label}"
Category: ${node.category}
Year: ${node.year}

Provide a JSON response with:
1. "summary": A concise 2-sentence summary
2. "significance": Why this entity is significant in the "Silicon Age" (transistors to AI)
3. "keyFacts": Array of 3-5 interesting facts or achievements

Be specific with dates, numbers, and achievements.
`;

    try {
        const result = await model.generateContent(prompt);
        const response = result.response;
        const text = response.text();

        // Clean JSON from markdown code blocks
        const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/) ||
            text.match(/\{[\s\S]*\}/);

        if (jsonMatch) {
            const json = jsonMatch[1] || jsonMatch[0];
            return JSON.parse(json) as AIResponse;
        }

        return null;
    } catch (error) {
        console.error(`Error for ${node.id}:`, error);
        return null;
    }
}

async function main() {
    console.log('🚀 Starting cache generation...\n');

    const nodes = extractNodes();
    console.log(`📦 Found ${nodes.length} nodes\n`);

    const cache: Record<string, AIResponse> = {};
    let success = 0;
    let failed = 0;

    // Process in batches to avoid rate limits
    const BATCH_SIZE = 5;
    const DELAY_MS = 2000; // 2 seconds between batches

    for (let i = 0; i < nodes.length; i += BATCH_SIZE) {
        const batch = nodes.slice(i, i + BATCH_SIZE);

        console.log(`Processing batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(nodes.length / BATCH_SIZE)}...`);

        const results = await Promise.all(
            batch.map(async (node) => {
                const result = await generateForNode(node);
                if (result) {
                    cache[node.id] = result;
                    success++;
                    process.stdout.write('✓');
                } else {
                    failed++;
                    process.stdout.write('✗');
                }
                return result;
            })
        );

        console.log('');

        // Rate limit delay
        if (i + BATCH_SIZE < nodes.length) {
            await new Promise(resolve => setTimeout(resolve, DELAY_MS));
        }
    }

    // Generate staticCache.ts
    const outputPath = path.join(__dirname, '../services/staticCache.ts');
    const output = `
import { AIResponse } from "../types";

// Auto-generated by scripts/generateCache.ts
// Generated at: ${new Date().toISOString()}
// Total nodes: ${success}

export const STATIC_CACHE: Record<string, AIResponse> = ${JSON.stringify(cache, null, 2)};
`;

    fs.writeFileSync(outputPath, output);

    console.log(`\n✅ Cache generated!`);
    console.log(`   Success: ${success}`);
    console.log(`   Failed: ${failed}`);
    console.log(`   Output: ${outputPath}`);
}

main().catch(console.error);
