import { GraphData, NodeData, LinkData, Category, LinkType } from '../../types';

/**
 * Generate TypeScript code for constants.ts from in-memory data
 */
export function generateCode(data: GraphData): string {
  const lines: string[] = [];

  // Header
  lines.push('// === GENERATED CODE ===');
  lines.push('// Generated by Debug Mode - Data Manager');
  lines.push('// Copy this code and paste it into constants.ts');
  lines.push('');
  lines.push('import { GraphData, Category, LinkType } from "./types";');
  lines.push('import {');
  lines.push('  createCompany, createPerson, createTech,');
  lines.push('  link, linkRival, linkPartner');
  lines.push('} from "./utils/builders";');
  lines.push('');
  lines.push('export const INITIAL_DATA: GraphData = {');
  lines.push('  nodes: [');

  // Sort nodes: Technology -> Company -> Person
  const sortedNodes = [...data.nodes].sort((a, b) => {
    const categoryOrder = { TECHNOLOGY: 0, COMPANY: 1, PERSON: 2 };
    const catDiff = (categoryOrder[a.category] || 3) - (categoryOrder[b.category] || 3);
    if (catDiff !== 0) return catDiff;
    // Then by year
    const yearDiff = (a.year || 0) - (b.year || 0);
    if (yearDiff !== 0) return yearDiff;
    // Then alphabetically
    return a.label.localeCompare(b.label);
  });

  // Group by category
  const techNodes = sortedNodes.filter(n => n.category === Category.TECHNOLOGY);
  const companyNodes = sortedNodes.filter(n => n.category === Category.COMPANY);
  const personNodes = sortedNodes.filter(n => n.category === Category.PERSON);

  // Generate TECHNOLOGY nodes
  if (techNodes.length > 0) {
    lines.push('    // === TECHNOLOGIES ===');
    techNodes.forEach((node, idx) => {
      lines.push(generateTechNode(node, idx === techNodes.length - 1 && companyNodes.length === 0 && personNodes.length === 0));
    });
  }

  // Generate COMPANY nodes
  if (companyNodes.length > 0) {
    lines.push('');
    lines.push('    // === COMPANIES ===');
    companyNodes.forEach((node, idx) => {
      lines.push(generateCompanyNode(node, idx === companyNodes.length - 1 && personNodes.length === 0));
    });
  }

  // Generate PERSON nodes
  if (personNodes.length > 0) {
    lines.push('');
    lines.push('    // === PEOPLE ===');
    personNodes.forEach((node, idx) => {
      lines.push(generatePersonNode(node, idx === personNodes.length - 1));
    });
  }

  lines.push('  ],');
  lines.push('');
  lines.push('  links: [');

  // Sort links: Creates -> Powers -> Contributes -> Engages
  const sortedLinks = [...data.links].sort((a, b) => {
    const typeOrder = { CREATES: 0, POWERS: 1, CONTRIBUTES: 2, ENGAGES: 3 };
    return (typeOrder[a.type] || 4) - (typeOrder[b.type] || 4);
  });

  // Group by type
  const createLinks = sortedLinks.filter(l => l.type === LinkType.CREATES);
  const powerLinks = sortedLinks.filter(l => l.type === LinkType.POWERS);
  const contributeLinks = sortedLinks.filter(l => l.type === LinkType.CONTRIBUTES);
  const engageLinks = sortedLinks.filter(l => l.type === LinkType.ENGAGES);

  // Generate CREATES links
  if (createLinks.length > 0) {
    lines.push('    // === CREATES ===');
    createLinks.forEach((link, idx) => {
      lines.push(generateLink(link, idx === createLinks.length - 1 && powerLinks.length === 0 && contributeLinks.length === 0 && engageLinks.length === 0));
    });
  }

  // Generate POWERS links
  if (powerLinks.length > 0) {
    lines.push('');
    lines.push('    // === POWERS ===');
    powerLinks.forEach((link, idx) => {
      lines.push(generateLink(link, idx === powerLinks.length - 1 && contributeLinks.length === 0 && engageLinks.length === 0));
    });
  }

  // Generate CONTRIBUTES links
  if (contributeLinks.length > 0) {
    lines.push('');
    lines.push('    // === CONTRIBUTES ===');
    contributeLinks.forEach((link, idx) => {
      lines.push(generateLink(link, idx === contributeLinks.length - 1 && engageLinks.length === 0));
    });
  }

  // Generate ENGAGES links
  if (engageLinks.length > 0) {
    lines.push('');
    lines.push('    // === ENGAGES ===');
    engageLinks.forEach((link, idx) => {
      lines.push(generateLink(link, idx === engageLinks.length - 1));
    });
  }

  lines.push('  ]');
  lines.push('};');

  return lines.join('\n');
}

function generateTechNode(node: NodeData, isLast: boolean): string {
  const parts: string[] = [];
  parts.push(`    createTech({`);
  parts.push(`      id: '${node.id}',`);
  parts.push(`      label: '${escapeString(node.label)}',`);
  parts.push(`      year: ${node.year || 2000},`);
  parts.push(`      description: '${escapeString(node.description || '')}',`);
  if (node.techCategoryL1) parts.push(`      techCategoryL1: '${node.techCategoryL1}',`);
  if (node.techCategoryL2) parts.push(`      techCategoryL2: '${node.techCategoryL2}',`);
  if (node.impactRole) parts.push(`      impactRole: '${node.impactRole}',`);
  parts.push(`    })${isLast ? '' : ','}`);
  return parts.join('\n');
}

function generateCompanyNode(node: NodeData, isLast: boolean): string {
  const parts: string[] = [];
  parts.push(`    createCompany({`);
  parts.push(`      id: '${node.id}',`);
  parts.push(`      label: '${escapeString(node.label)}',`);
  parts.push(`      year: ${node.year || 2000},`);
  parts.push(`      description: '${escapeString(node.description || '')}',`);
  if (node.companyCategories && node.companyCategories.length > 0) {
    parts.push(`      companyCategories: [${node.companyCategories.map(c => `'${c}'`).join(', ')}],`);
  }
  if (node.impactRole) parts.push(`      impactRole: '${node.impactRole}',`);
  parts.push(`    })${isLast ? '' : ','}`);
  return parts.join('\n');
}

function generatePersonNode(node: NodeData, isLast: boolean): string {
  const parts: string[] = [];
  parts.push(`    createPerson({`);
  parts.push(`      id: '${node.id}',`);
  parts.push(`      label: '${escapeString(node.label)}',`);
  parts.push(`      year: ${node.year || 1900},`);
  parts.push(`      description: '${escapeString(node.description || '')}',`);
  if (node.primaryRole) parts.push(`      primaryRole: '${node.primaryRole}',`);
  if (node.impactRole) parts.push(`      impactRole: '${node.impactRole}',`);
  parts.push(`    })${isLast ? '' : ','}`);
  return parts.join('\n');
}

function generateLink(link: LinkData, isLast: boolean): string {
  const sourceId = typeof link.source === 'string' ? link.source : link.source.id;
  const targetId = typeof link.target === 'string' ? link.target : link.target.id;

  // Special handling for ENGAGES with icons
  if (link.type === LinkType.ENGAGES) {
    if (link.icon === 'RIVALRY') {
      return `    linkRival('${sourceId}', '${targetId}')${isLast ? '' : ','}`;
    } else if (link.icon === 'HEART') {
      return `    linkPartner('${sourceId}', '${targetId}')${isLast ? '' : ','}`;
    }
  }

  // Standard link
  return `    link('${sourceId}', '${targetId}', LinkType.${link.type})${isLast ? '' : ','}`;
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Download generated code as file
 */
export function downloadAsFile(code: string, filename: string = 'generated-constants.ts'): void {
  const blob = new Blob([code], { type: 'text/typescript' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
